eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: EMPLOYEE
              uri: lb://EMPLOYEE
              predicates:
                - Path=/api/employees/**
              filters:
                - AuthFilter

            - id: ADDRESS
              uri: lb://ADDRESS
              predicates:
                - Path=/api/addresses/**
              filters:
                - AuthFilter

            - id: AUTH
              uri: lb://AUTH
              predicates:
                - Path=/api/auth/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG